palantir/documentalist

src/client.ts

it can be inferred more reliably from the page that contains this heading node.

remove pageReference from IHeadingNode

---

.npmignore

instead of ignoring everything and including specifics (which did not include cli.js).
tested via `npm install path/to/documentalist` locally. does not produce the error in https://circleci.com/gh/palantir/blueprint/1994.

rewrite npmignore to ignore specifics

---

cli.js
package.json
src/client.ts
src/documentalist.ts
src/plugins/markdown.ts
src/plugins/plugin.ts
test/documentalistTests.ts
test/fixtures/component.tsx
test/pluginsTests.ts
yarn.lock

update npm packages and code as necessary.
`IApi<T extends object>` enforces that each plugin must return an `object`.

TypeScript 2.2 + TSlint 4.5

---

docs/index.html
src/documentalist.ts
src/plugins/css.ts
src/plugins/markdown.ts
src/plugins/typescript.ts
theme/index.pug

- add `documentalist.objectify` function to convert array to map
- update theme and plugins
- namespace plugin interfaces so the nav is more legible

plugins return maps instead of arrays

---

src/compiler.ts
src/documentalist.ts
src/index.ts
src/plugins/css.ts
src/plugins/markdown.ts
src/plugins/plugin.ts
src/plugins/typescript.ts
test/compilerTests.ts

all the `renderBlock` logic moves to a separate class :ok_hand:.
also swap `compile()` args so files comes first--easier usage if plugin doesn't need compiler.

new Compiler class is passed to plugins

---

src/compiler.ts
src/plugins/kss.ts
src/plugins/plugin.ts

KssPlugin markdownifies documentation + markup for syntax highlighting

add renderMarkdown to ICompiler

---

docs/assets/index.js
src/_nav.md
src/client.ts
src/docs.md
src/page.ts
src/plugins/markdown.ts
test/pluginsTests.ts
theme/index.pug

`MarkdownPlugin` outputs `{ nav, pages }` where `nav` is tree describing page/heading layout and `pages` is a map of data for each page.
new `PageMap` class wraps a `Map` with some use-case-specific operations to simplify usage.
update the pug theme so it's ready to support multiple pages.

MarkdownPlugin generates nav layout too!

---

src/client.ts
src/compiler.ts
src/page.ts
src/plugins/markdown.ts
test/pluginsTests.ts

- introduce `IHeadingTag extends ITag` with route & level to make rendering headings really easy.
- Compiler turns all `@#+` tags into `tag: "heading"`, but can't populate `route` yet.
- Page operates on "page" and "heading" tags (so readable!).
- MarkdownPlugin populates `route` property in pages and nav with fully qualified path to the resource: `path/to/page[.heading]`.
- remove obsolete heading/pageReference options as all slugification happens inside MarkdownPlugin.

MarkdownPlugin populates `route` property

---

package.json
src/client.ts
src/compiler.ts
src/page.ts
src/plugins/markdown.ts
src/plugins/plugin.ts
test/compilerTests.ts

- `IPageData` extends `IBlock`, compiler methods also speak `IBlock`
- this reduces the naming surface area because `contents` always refers to rendered `StringOrTag[]` and `contentsRaw` is always a string.
- new interface `INavigable` for route & level used in `IHeadingTag` & `IHeadingNode`
- `IPageNode` extends `IHeadingNode` for maximal reuse (also rename depth &rarr; level)
- type guards take `any` arg & check existence first

API refactors

---

README.md
cli.js
src/__tests__/compiler.test.ts
src/__tests__/markdown.test.ts
src/compiler.ts
src/documentalist.ts
src/plugins/typescript.ts

add options to compiler and typescript plugin. documentalist passes its options straight to compiler.
swap order of `Documentalist` constructor args so no need for empty plugins array every time.
⚠️ remove default plugins from `Documentalist.create()` because they have options that will want to be set.

options options options

---

docs/index.html
src/client/index.ts
src/client/kss.ts
src/client/markdown.ts
src/client/typescript.ts
src/client/utils.ts
src/compiler.ts
src/plugins/index.ts
src/plugins/kss.ts
src/plugins/markdown.ts
src/plugins/plugin.ts
src/plugins/typescript.ts

This refactor will allow typescript projects to `import ... from "documentalist/dist/client";` to receive typings for documentalist output that will work in a browser environment without bringing in server-side typings.

Isolate client typings

---

src/__tests__/__fixtures__/classes.ts
src/__tests__/__snapshots__/typescript.test.ts.snap
src/__tests__/typescript.test.ts
src/plugins/typescript/index.ts
src/plugins/typescript/visitor.ts

`excludePaths` & `excludeNames` & `includeDeclarations`, like the original ts-quick-docs solution

more options!

---

src/plugins/typescript/index.ts
src/plugins/typescript/visitor.ts

- :fire: `excludePaths` is not passed to typedoc but rather used at the same time as `excludeNames` when visiting children
- this means string patterns are interpreted as regexes, not globs.
- accepts `string | RegExp` patterns

excludePaths works like excludeNames

---

docs/index.html
package.json
yarn.lock

typedoc 0.10.0 now supports typescript 2.7!
this is not a breaking change, can be shipped as 1.1.0.

upgrade typedoc, use ts 2.7

---

src/__tests__/__snapshots__/markdown.test.ts.snap
src/__tests__/markdown.test.ts
src/client/markdown.ts
src/plugins/markdown.ts

path to markdown file. this is necessary for supporting "edit" links like https://github.com/palantir/blueprint/issues/101

add markdown filePath property

---

cli.js
src/__tests__/npm.test.ts
src/client/compiler.ts
src/client/index.ts
src/client/npm.ts
src/compiler.ts
src/launch.ts
src/plugins/index.ts
src/plugins/kss.ts
src/plugins/markdown.ts
src/plugins/npm.ts

- new `sourceBaseDir` option for `Documentalist` controls relative pathing for `sourcePath` in MD and NPM
- new `NpmPlugin`!
- `excludePrivate`, `excludePaths` options
- parses package.json files, gets more data from `npm info` if possible (async call to npm registry)
- if package is private or unpublished then it uses available package.json
- emits name, desc, latest/next, all versions

NPM plugin

---

packages/docs/src/index.ts
packages/docs/theme/index.pug
packages/docs/theme/mixins.pug

hi folks! monorepo change is very nice 👍
was poking through the docs and decided to file down a few rough edges.
- fix ID for the default page so it doesn't load blank
- add "API Reference" heading to separate docs page (Compiler/Client) from list of entity names
- support heading tag to fix the first line of Compiler & Client pages
- add package name to interface docs to clarify where an entity can be found

little docs site fixes

---

packages/client/package.json
packages/compiler/package.json
packages/compiler/src/documentalist.ts
packages/compiler/src/plugins/typescript/index.ts
packages/compiler/src/plugins/typescript/typestring.ts
packages/compiler/src/plugins/typescript/visitor.ts
packages/docs/package.json
tslint.json
yarn.lock

Upgrade TypeScript to 3.5.2
Open to discussion on this, but also swapped the `typedoc` dep for `@gerrit0/typedoc`, which is cut from master of the same repo but published under a separate namespace. I was thinking we can at least get documentalist on TypeScript 3.5.x for consumers, and then when `typedoc` finally releases we can swap it back

Upgrade typescript, swap typedoc dep

---

packages/client/package.json
packages/compiler/package.json
packages/docs/package.json
yarn.lock

+ Upgrade TypeScript to [~3.8.3](https://github.com/microsoft/TypeScript/releases/tag/v3.8.3)
+ Upgrade typedoc to [`^0.17.4`](https://github.com/TypeStrong/typedoc/releases/tag/0.17.4)
This should allow consumers to upgrade to TypeScript ~3.8.3 with a clean `yarn.lock`

Upgrade TypeScript to ~3.8.3 and typedoc to ^0.17.4

---

packages/compiler/src/plugins/npm.ts

This fixes a `spawn NOENT` error when running the compiler on win platforms.
Related to [issue with compiling docs-data in BlueprintJS](https://github.com/palantir/blueprint/issues/3062#issuecomment-439363356).

fix: NOENT error on win platform
